### ISSUE TITLE
Hi. Gratitude for the lib. Do they have a dictionary or clear explains for your graphics? Thank you. 

### ISSUE THREAD

**Issue by jcsbravo** [stefan-jansen/pyfolio-reloaded#17]
## Problem Description

**Please provide a minimal, self-contained, and reproducible example:**
```python
[Paste code here]
```

**Please provide the full traceback:**
```python
[Paste traceback here]
```

**Please provide any additional information below:**

## Versions

* Pyfolio version:
* Python version:
* Pandas version:
* Matplotlib version:

**Comment by stefan-jansen** [comment]
Thanks for your interest. Could you please be more specific about what you are looking for?
