### ISSUE TITLE
Unable to import pyfolio reloaded

### ISSUE THREAD

**Issue by groundedtako** [stefan-jansen/pyfolio-reloaded#21]
## Problem Description
Cannot import pyfolio_reloaded or pyfolio

**Please provide a minimal, self-contained, and reproducible example:**
```python
# Import a few libraries we need
%matplotlib inline
from zipline import run_algorithm
from zipline.api import order_target_percent, symbol,  \
    schedule_function, date_rules, time_rules
from datetime import datetime
import pandas as pd
import pytz

# note pyfolio by quantopian is no longer maintend, pip install pyfolio-reloaded to continue
import pyfolio_reloaded as pf
```

**Please provide the full traceback:**
```python
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 11
      8 import pytz
     10 # note pyfolio by quantopian is no longer maintend, pip install pyfolio-reloaded to continue
---> 11 import pyfolio_reloaded as pf
     14 def initialize(context):
     15     # Which stocks to trade
     16     dji = [
     17         "AAPL",
     18         "AXP",
   (...)
     46         "XOM",  
     47     ]

ModuleNotFoundError: No module named 'pyfolio_reloaded'
```

**Please provide any additional information below:**
python -c "import pyfolio_reloaded as pf" this command fails in the terminal. I've made sure that the package is installed in the right virtual environment, and that it's path is in the path variables.

## Versions

* Pyfolio version: pyfolio-reloaded==0.9.4
* Python version: 3.9
* Pandas version: pandas==1.5.2
* Matplotlib version: matplotlib==3.6.2

**Comment by stefan-jansen** [comment]
Please note that [it's still](https://pyfolio.ml4trading.io/notebooks/single_stock_example.html) 
```
import pyfolio
```
