### ISSUE TITLE
PyFolio Roundtrip Error

### ISSUE THREAD

**Issue by firmai** [stefan-jansen/pyfolio-reloaded#33]
https://colab.research.google.com/drive/17ORtx43vIDSgUI8y0ozKTYf5pdHNtfsa?usp=sharing

Any help would be greatly appreciated

/usr/local/lib/python3.10/dist-packages/pyfolio/round_trips.py in extract_round_trips(transactions, portfolio_value)
    244                     {
    245                         "pnl": pnl,
--> 246                         "open_dt": cur_open_dts[0],
    247                         "close_dt": dt,
    248                         "long": price < 0,

IndexError: list index out of range

**Comment by ava6969** [comment]
i had this issue when i had fractional quantities in my trades

**Comment by firmai** [comment]
Yup, I think that is it!

**Comment by stefan-jansen** [comment]
Pull requests are welcome. Closing for now due to lack of activity; feel free to reopen if you would like to discuss/address.
