### ISSUE TITLE
if all round_trips.profitable equal True, the next step will fail

### ISSUE THREAD

**Issue by pg-adm1n** [stefan-jansen/pyfolio-reloaded#36]
https://github.com/stefan-jansen/pyfolio-reloaded/blob/05adbf7c5f2f8545a458cef8ddca8319344d6933/src/pyfolio/plotting.py#L1952

![image](https://github.com/stefan-jansen/pyfolio-reloaded/assets/13415537/b5ad7b8c-da12-4380-9b2a-cdf66dc9dca7)

**Comment by stefan-jansen** [comment]
Pull requests are welcome! Closing for now due to lack of activity, feel free to reopen if you'd like to discuss.
